# Generated by Django 2.2.2 on 2020-02-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200221_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlike',
            name='product',
        ),
        migrations.AddField(
            model_name='productlike',
            name='product',
            field=models.ManyToManyField(related_name='liked_product', to='products.Products'),
        ),
    ]
